services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-observe:v1
    container_name: laravel-observe
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/database/sqlite_db
      - ./storage/logs:/app/storage/logs
    environment:
      - OTEL_PHP_AUTOLOAD_ENABLED=${OTEL_PHP_AUTOLOAD_ENABLED}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}

volumes:
  sqlite_data:
    driver: local