services:
  laravel-app:
    image: laravel-app:v1
    container_name: laravel_frankenphp
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/database/sqlite_db
    environment:
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=laravel-app
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.136.201:5080/api/default
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic cm9vdEBleGFtcGxlLmNvbTpoUFRHcG5pNXhaejBodDRY

volumes:
  sqlite_data:
    driver: local